### ISSUE TITLE
Can't get base16-vim to work on Chromebook

### ISSUE THREAD

**Issue by mjackson** [chriskempson/base16-vim#164]
I'm using bash inside hterm on a Chromebook. I'm using the default hterm settings, which sets `$TERM` to `xterm-256color`.

I'm using base16-shell to color my shell, and it's working beautifully. Thank you! However, no matter what I try I can't get base16-vim to work :/

As suggested in the base16-shell README, I'm using the following in my `~/.vimrc`:

```vim
if filereadable(expand("~/.vimrc_background"))                                                                                      
  let base16colorspace=256                                                                                                          
  source ~/.vimrc_background                                                                                                        
endif 
```

My `~/.vimrc_background` is working correctly, but I keep getting the blue bars in vim! I've tried toggling the `let base16colorspace` line, and even messing around with `set t_Co=256` which seems to change things, but doesn't make them any better. Below is a screenshot of what I see:

![screenshot 2017-12-06 at 12 00 32 am](https://user-images.githubusercontent.com/92839/33650915-c0a6c93e-da18-11e7-9fc1-b76988ea5258.png)

Any suggestions for how to fix? I've attached the output of `vim --version` below:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 29 2017 01:19:54)
Included patches: 1-586
Compiled by chronos@localhost
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
-clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -Wall -Wextra -Wshadow -Wmissing-prototypes -Wunreachable-code -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1   -DEXITFREE    
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/local/lib/perl5/5.24.1/x86_64-linux/CORE   -Wl,--as-needed -o vim        -lm -lelf -lnsl   -lncurses -lacl -lattr -ldl   -Wl,-E -Wl,-rpath,/usr/local/lib/perl5/5.24.1/x86_64-linux/CORE  -fstack-protector-strong -L/usr/local/lib  -L/usr/local/lib/perl5/5.24.1/x86_64-linux/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/local/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -Wl,-R/usr/local/lib64 -L/usr/local/lib64 -lruby -lpthread -lgmp -ldl -lcrypt -lm
```

Thanks!

**Comment by jlesquembre** [comment]
I fixed the blue line problem with `set termguicolors`  [link to docs](https://neovim.io/doc/user/options.html#'termguicolors')

The link is to the neovim documentation, but you have the same option in vim. Let me know if that helps, maybe we should add some information about `termguicolors ` on the readme

**Comment by mjackson** [comment]
YES! `set termguicolors` worked for me! Thank you so much! I was working on this for like 4 hours yesterday... I still don't totally understand how everything works, which is a little unnerving. I feel like the README (and probably even the main base16 repo's README) could use a little more info on what exactly is going on. i.e. what is a "color space"? And why is it important to map colors? And why do some terminals work and others don't?

Anyway, thanks again for the help @jlesquembre. I really appreciate it!

**Comment by jlesquembre** [comment]
@mjackson Glad to hear that it worked
