### ISSUE TITLE
Braces Disappearing in terminal Vim

### ISSUE THREAD

**Issue by damienstanton** [chriskempson/base16-vim#63]
Using Vim 7.4.273 on Ubuntu 14.10.

In the Gnome terminal, when the cursor is over any brace character (or to the right of the character), both braces disappear instead of being highlighted. This happens on all syntax highlighting.

![1](https://cloud.githubusercontent.com/assets/4822375/6574588/f0131740-c6fc-11e4-8f9c-0dfa96a51a9d.png)
`Normal`

![2](https://cloud.githubusercontent.com/assets/4822375/6574589/f1d8f3a6-c6fc-11e4-9769-9421e8407f9a.png)
`Curly braces disappear`

![3](https://cloud.githubusercontent.com/assets/4822375/6574593/f8093894-c6fc-11e4-941a-284bff1c1a08.png)
`Curly braces reappear but parens disappear`

As shown above, it does not occur when the cursor is to the _left_ of the brace character. The issue does not appear at all in GVim.

**Comment by edenist** [comment]
I'd like to confirm this is happening as well.

Using Atelier Seaside Dark theme in both gnome-terminal and in vim.

**Comment by ntolkachev** [comment]
Confirm, Ubuntu 15.04

**Comment by cbruun** [comment]
I am seeing this as well on Ubuntu 14.04 using the solarized theme.

Any ideas what could be causing this?

**Comment by oryband** [comment]
Happens on vim, tmux, eighties

**Comment by chriskempson** [comment]
How are you scheming your terminals? base16-shell?

**Comment by oryband** [comment]
@chriskempson yes, using base16-shell-eighties-dark

**Comment by oryband** [comment]
@chriskempson also Xresources are set correctly

**Comment by chriskempson** [comment]
I'm unable to replicate this though admittedly I'm not running Gnome Terminal or even Linux, as such I don't really have a way of fixing this sorry.

![image](https://cloud.githubusercontent.com/assets/473831/16413784/15d6a270-3d2c-11e6-8065-6d36986852a9.png)

**Comment by oryband** [comment]
@chriskempson virtual machine? note this also happens on urxvt + tmux

**Comment by chriskempson** [comment]
@oryband True but I was sort of hoping that someone else might get around to fixing this and submit a PR 😉 

I have just pushed an update to this repo, can you confirm the issue still exists?

**Comment by oryband** [comment]
@chriskempson this seems to be magically fixed. @damienstanton can you confirm?

**Comment by oryband** [comment]
@chriskempson any idea what caused this?

**Comment by chriskempson** [comment]
I'm not entirely sure, though I do remember an issue like this that was resolved on base16-builder so thought it might just be that this repo was rather stale (my fault sorry, I'll keep on top of it in the future).

**Comment by oryband** [comment]
great! thanks for the quick reply and resolving

**Comment by joninvski** [comment]
Just wanted to leave a note. I still have the same problem if I use roxterm.

If I use gnome-terminal the problem disappears.

**Comment by chriskempson** [comment]
Can anyone else confirm if this works/doesn't work on roxterm? Don't really have the time to setup a VM for this sorry.

**Comment by ncs-alane** [comment]
This is still an issue in lxterminal.

**Comment by chriskempson** [comment]
@ncs-alane and your using an up to date version of base16-vim?

**Comment by ncs-alane** [comment]
@chriskempson yes indeed.

**Comment by selaux** [comment]
I can still reproduce this with current master and xfce4-terminal any update?

**Comment by estebanz01** [comment]
I was able to replicate the issue with a black background and `base16_default-dark` them under tmux 2.0 with or without `let base16colorspace=256` and .

### Inside tmux
If I have a black background in vim and use white to highlight all the parens and brackets, when the cursor pass through one of those chars, it fails to retrieve the correct colour to be used as cursor background.

![parens](https://cloud.githubusercontent.com/assets/2417465/18646453/34b8adbe-7e77-11e6-9b31-44a44c7fab7c.png)

![parens1](https://cloud.githubusercontent.com/assets/2417465/18646455/34ba0704-7e77-11e6-930a-f8c650bc6be8.png)

### Outside tmux
If I have a black background in vim and use white to highlight all the parens and brackets, when the cursor pass through one of those chars, it retrieves the correct colour to be used as cursor background.

![parens2](https://cloud.githubusercontent.com/assets/2417465/18646625/05077202-7e78-11e6-9643-ac129a15ee9f.png)

![parens3](https://cloud.githubusercontent.com/assets/2417465/18646624/050684d2-7e78-11e6-9922-f178e15f554f.png)

I'm not a vim expert, so I don't know which files should I modify in order to see why it's failing and how to fix it. Just in case, I'll paste my tmux conf here:

```
### General
###########################################################################

# Enable UTF-8
setw -g utf8 on
set-option -g status-utf8 on

# Scrollback/History limit
set -g history-limit 500000

# Index Start
set -g base-index 1

# Reindex windows
set-option -g renumber-windows on

# Mouse
setw -g mode-mouse on
set-option -g mouse-select-pane on
set -g mouse-utf8 off

# Force reload of config file
unbind r
bind r source-file ~/.tmux.conf

# Second prefix (Space bar)
set -g prefix2 C-space

### Keybinds
###########################################################################
bind-key -n F1 select-window -t 1 # Select window 1
bind-key -n F2 select-window -t 2 # Select window 2
bind-key -n F3 select-window -t 3 # Select window 3
bind-key -n F4 select-window -t 4 # Select window 4
bind-key -n F5 select-window -t 5 # Select window 5
bind-key -n F6 select-window -t 6 # Select window 6
bind-key -n F7 select-window -t 7 # Select window 7
bind-key -n F8 select-window -t 8 # Select window 8
bind-key -n F9 select-window -t 9 # Select window 9
bind-key -n F10 select-window -t 10 # Select window 10
bind-key -n IC new-window # New window with Insert key

### Pretty term
#########################################################################
# Status bar at top
set-option -g status-position top

# Statusbar Color Palatte
set-option -g status-justify left
set-option -g status-bg black
set-option -g status-fg white
set-option -g status-left-length 40
set-option -g status-right-length 80

### Status Windows
# Session name
set -g status-left '#[fg=colour166,bold]Blah '

# Highlight current window
set-window-option -g window-status-current-bg blue
# Notification
setw -g monitor-activity on
set -g visual-activity on
# set-option -g bell-action any
# set-option -g visual-bell on

# Autorename sanely.
setw -g automatic-rename on

# Better name management
bind c new-window -c "#{pane_current_path}"
```

**Comment by stofstik** [comment]
I have a similar issue.
Ubuntu 16.04, gnome-terminal, base16-shell.
Bracket highlighting works, but cursor blink is inverted.
Meaning that the matching paren lights up and the cursor disappears just before starting to blink again.
I still now where the cursor is, but it is extremely confusing when pair programming.
Is there a fix for this?

**Comment by muhang** [comment]
Posting this in hopes it may be helpful, I had this issue with Ubuntu 16.04, tmux, and base16 color schemes in both vim and gnome-terminal. It turned out I had included `set background=dark` in my .vimrc from when I used solarized; removing that line fixed the issue completely.

**Comment by estebanz01** [comment]
Confirm fixed after `:PluginUpdate`. Yay! :tada: 

thanks @Naissur

**Comment by Naissur** [comment]
Glad it helped :)

**Comment by tmccombs** [comment]
I am still having the issue described by stofstik, where in normal mode when the cursor is over a brace it highlight the matching brace but not the actual cursor. I am using nvim, and it happens in termite, terminator, and konsole, but not in xterm or urxvt.

**Comment by Naissur** [comment]
@tmccombs In vim GUI it is different - can you try it in `gnome-terminal`?

**Comment by tmccombs** [comment]
I can reproduce in gnome-terminal as well:
![image](https://cloud.githubusercontent.com/assets/2541726/23836531/786eeb12-073f-11e7-99b2-afce0d1cb193.png)

the cursor is on the top brace.

I also noticed that  if the terminal loses focus then the the cursor does show correctly (although the cursor and match hilight look identical, so it is still hard to tell where the cursor actually is).

**Comment by tmccombs** [comment]
Also I should have mentioned that termguicolors is enabled in neovim.

**Comment by tmccombs** [comment]
If I do `hi MatchParen guifg=none` it seems to work correctly. I think the fix is to not set the guifg for MatchParen, just as ctermfg is no longer set.

**Comment by Naissur** [comment]
You're right, @tmccombs. I agree - the fix is to remove the foreground from guifg in gui. Can you do that? :slightly_smiling_face:

**Comment by jlesquembre** [comment]
@tmccombs @Naissur is this still an isssue? I can't reproduce it (with termguicolors enabled on neovim). Maybe PR #137 fixed it for you, but is annoying me because now I cannot see parentheses when I put them in a comment and my cursor is on them (fg and bg color are the same )

**Comment by damienstanton** [comment]
Since no one has updated this issue in over a year (and ostensibly no one has reproduced the issue), and I was the OP, I am closing.
